### ISSUE TITLE
Compatibility with Imagify folder

### ISSUE THREAD

**Issue by jdutant** [Philosophie-ch/dltc-env#5]
MWE in dialectica's workhouse folder > tests > imagify-test. Run `sh make.sh` in the docker for a test (see that file for the test commands). 

## Expected behaviour

Running the test should create a folder `_imagify_files` and generate pdf/svg files in that folder.  

## Actual behaviour

the `imagify_files` folder is created, but no files appear in it. 

## Background 

imagify.lua uses the following lua commands. Lua is embedded in Pandoc so they'll be run by whichever user Pandoc has:

- os.rename (https://www.lua.org/pil/22.html)
- os.execute (https://www.lua.org/pil/22.2.html)

The latter is used to "runs a system command" (probably in a new shell, same user?). The system commands it runs are:

* latexmk
* dvisvgm

In order: it runs latexmk (and, if converting to SVG, dvisvgm), then uses os.rename to move the file in a folder `_imagify_files` in the user's folder. 

When running the test, it looks as if only the os.rename step fails: latexmk does go through runs for each image, `_imagify_files` is created, but no file is moved to it. Though, it could also be that the dvisvgm step fails silently.

**Comment by alebg** [comment]
@jdutant Taking a look. Will let you know if the problem comes from the way we're using docker compose (e.g., because of permissions) (i.e., problem comes from this repo), or if it's some dependency problem in the container (i.e., problem is in the dockerfiles / build process, which are in their own repo. I've splitted the projects because the dockerfiles one contains private files like the fonts)

**Comment by philo-ch** [comment]
@jdutant what's the format of the output files expected in  `_imagify_files`?

**Comment by alebg** [comment]
@jdutant what's the format of the output files expected in _imagify_files?

**Comment by alebg** [comment]
@jdutant I think the issue is how lua manages moving files between different file systems with `os.remove`, or something of the kind. I made this change starting in line 985 of `imagify.lua`:

```lua
            print('Renaming '..result..' to '..fileAbs)
            os.execute('mv ' .. result .. ' ' .. fileAbs)
            result = fileRelativeToJob
```
And with the minimal example I got two svg files in the `_...` folder. What do you think about this solution? If we keep using the docker container, then the behaviour should be consistent in all machines

**Comment by jdutant** [comment]
I did a few more tests and found the source of the bug. Lua's `os.rename` doesn't work in the docker. 

In the Imagify filter, created image files are exported using Lua's `os.rename` command like so (replacing variables with their actual value at this point in the script, line 986):

``` lua
os.rename ('source.dvi.svg', '/home/copyeditor/dltc-workhouse/tests/imagify-test/_imagify_files/62e6e5fd35195320591c728bd266888025c0dca3.svg')
```

At that point in Imagify's execution, the working folder is set by Pandoc to a temporary folder where the filter creates a TeX file, compiles it to PDF with latexmk, and converts it to SVG with dvisvgm (`/tmp//tmp/imagify-973b4c23e20b84c6/' in the container). If I replace the script above with one that instead execute a `mv` command, the bug disappear:

``` lua
os.execute('mv '..'source.dvi.svg..' '../home/copyeditor/dltc-workhouse/tests/imagify-test/_imagify_files/62e6e5fd35195320591c728bd266888025c0dca3.svg')
```

So `os.rename`  (silently) fails to move the file, while `mv` can. I tried to make the first path absolute like the second:

``` lua 
os.rename ('/tmp/imagify-973b4c23e20b84c6/source.dvi.svg', '/home/copyeditor/dltc-workhouse/tests/imagify-test/_imagify_files/62e6e5fd35195320591c728bd266888025c0dca3.svg')
```

But that doesn't help. I'm not sure what prevents `os.rename` to do this right: permissions??

Why not simply use `mv` in Imagify? This fixes the bug, but makes the filter system-dependent. Imagify is a public filter; it must work with Windows, too.

One option would be to write a custom 'rename' function for the filter that calls `mv` on nix systems and `copyy` on windows ones.

**Comment by jdutant** [comment]
Meeting of minds! Further test: there are unnecessary `/./` in the absolute paths Imagify uses. I modified the script to remove them; no improvement.

**Comment by jdutant** [comment]
> And with the minimal example I got two svg files in the `_...` folder. What do you think about this solution? If we keep using the docker container, then the behaviour should be consistent in all machines

But Imagify would only work on Linux/MacOS. As hack we could have a custom version of imagify in the docker, but that's not good long term.

**Comment by alebg** [comment]
@jdutant  A lua-fied version of something we could do in python. Don't know if it's idiomatic in lua to do this, but it's an idea:

```lua
print('Writing '..result..' to '..fileAbs)
local inFile = io.open(result, "r")
local outFile = io.open(fileAbs, "w")

if inFile and outFile then
    outFile:write(inFile:read("*all"))
    inFile:close()
    outFile:close()
else
    if not inFile then
        print("ERROR: Could not open input file")
    end
    if not outFile then
        print("ERROR: Could not open output file")
    end
end

result = fileRelativeToJob
```

**Comment by jdutant** [comment]
Fixed in Imagify with https://github.com/dialoa/imagify/commit/dbcf1d51a204b24e08f947ff3bd1ef69fa9e1a5f
